#!/usr/bin/fish

set -l init "$(cat /sys/class/net/w*/statistics/rx_bytes | paste -sd '+')"




echo -n "Recording bandwidth. Press enter to stop."

sh -c "read -r lol"

set -l fin "$(cat /sys/class/net/w*/statistics/rx_bytes | paste -sd '+')"

set -l used $(numfmt --to=iec $(math "$fin - $init"))
set -l message $(echo $used "of bandwidth used.") 

notify-send $message
echo $message 

