#!/bin/bash

case $1 in
up)
    brightnessctl --device='kbd_backlight' set +5% > /dev/null
	notify-send -t 2000 "$(printf "Brightness up to: %s" "$(brightnessctl --device='kbd_backlight' info | grep % | awk -F' ' '{ print $4 }')")"
	;;
down)
    brightnessctl --device='kbd_backlight' set 5%- > /dev/null
	notify-send -t 2000 "$(printf "Brightness down to: %s" "$(brightnessctl --device='kbd_backlight' info | grep % | awk -F' ' '{ print $4 }')")"
	;;
esac
