#!/bin/sh

cur_vol=$(amixer get Master | tail -n1 | awk -F'[' '{ print $2 }' | tr ']' ' ' | xargs)

case $1 in
mute)
	if [ $cur_vol = "0%" ]; then
		new_vol=$(cat /tmp/last_mute)
		amixer set Master $new_vol || amixer set Master 20%
	else
		echo "$cur_vol" >/tmp/last_mute
		amixer set Master 0
	fi
	;;
up)
	if [ $cur_vol = "0%" ]; then
		new_vol=$(cat /tmp/last_mute)
		amixer set Master $new_vol || amixer set Master 1%
	else
		amixer set Master 1%+
	fi
	;;
down)
	amixer set Master 1%-
	;;
esac
