#!/bin/sh

on=$(amixer get Master | tail -n1 | awk -F'[' '{ print $3 }' | tr ']' ' ' | xargs)

case $1 in
mute)
    case $on in 
    "on")
        amixer set Master mute
        ;;
    "off")
        amixer set Master unmute
        ;;
    esac
	;;
up)
	amixer set Master 2%+
	;;
down)
	amixer set Master 2%-
	;;
esac
