#!/bin/sh

# cursorposinv() {
# 	normal_x=$(hyprctl cursorpos | awk -F',' '{print $1}')
# 	normal_y=$(hyprctl cursorpos | awk '{print $2}')
#
# 	window_height=$(hyprctl monitors | grep ' at ' | awk -F'@' '{print $1}' | awk -F'x' '{print $2}')
#
# 	better_pos=$(($window_height - $normal_y))
#
# 	echo "$normal_x, $better_pos"
# }

# swww query >/dev/null
# if [ $? -eq 1 ] ; then
#     swww init
# else
    wall=$(echo "$HOME/pix/wallpaper/$(ls ~/pix/wallpaper/ | shuf | head -n1)")

    # swww img $wall --transition-type grow --transition-pos "$(cursorposinv)" --transition-duration 2
    killall swaybg
    hyprctl dispatch exec "swaybg -m fill -i \"$wall\""
# fi


