#!/bin/sh

# . $HOME/.local/bin/env-wayland.sh # this just sources a few extra env variables

# Default things
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export XDG_CURRENT_DESKTOP=Hyprland

# Bug fixing
export WLR_RENDERER_ALLOW_SOFTWARE=1
export LIBSEAT_BACKEND=logind

export MESA_GL_VERSION_OVERRIDE=3.3
export MESA_GLSL_VERSION_OVERRIDE=330
export MESA_GLES_VERSION_OVERRIDE=3.1

exec dbus-run-session Hyprland $@
