#!/bin/sh

# A menu wrapper script for system functions.

menu="rofi -dmenu"

# For non-systemd init systems.
case "$(readlink -f /sbin/init)" in
    *runit*) hib="sudo -A zzz" ;;
    *openrc*) reb="sudo -A openrc-shutdown -r"; shut="sudo -A openrc-shutdown -p" ;;
esac

cmds="\
X kill window,     hyprctl kill
 lock hypr,       swaylock -eFfki ~/pic/wallpaper/nasaGrey.png
 leave hypr,      pkill Hyprland 
⏾ hibernate,       ${hib:-systemctl suspend-then-hibernate -i}
 reboot,          ${reb:-sudo -A reboot}
⏻ shutdown,        ${shut:-sudo -A shutdown -h now}"

choice="$(echo "$cmds" | cut -d',' -f 1 | $menu)" || exit 1

eval "$(echo "$cmds" | grep "^$choice," | cut -d ',' -f2-)"
