#!/bin/sh

# set as cronjob with: @daily

cd $XDG_MUSIC_DIR
command ls -1 *.ogg >~/.config/mpd/playlists/all.m3u
# grep ".jap" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/jap.m3u
# grep ".rock" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/rock.m3u
# grep ".city" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/city.m3u
# grep ".skitz" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/skitz.m3u

mpc update
# notify-send -t 5000 "All playlists have been resynced with contents of $XDG_MUSIC_DIR"
