#!/bin/sh

# set as cronjob with: @daily 

# songs are in the format of:
# (Song\file name)
#                 .playlist
#                          .file_type

# I only use opus for my music as I don't have any problems with the compression
# and they have a great/well supported tagging system

command ls -1 $XDG_MUSIC_DIR *.opus > ~/.config/mpd/playlists/all.m3u
grep ".jap" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/jap.m3u
grep ".rock" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/rock.m3u
grep ".city" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/city.m3u
grep ".skitz" ~/.config/mpd/playlists/all.m3u > ~/.config/mpd/playlists/skitz.m3u
mpc update
notify-send -t 8000 "All playlists have been resynced with contents of ~/music"
